### ISSUE TITLE
Could you explain the following formula n = n1? M, n1ij∼ N(0,1),  (14) in your paper? 

### ISSUE THREAD

**Issue by CLJcode** [zsyOAOA/VDNet#4]
![ss](https://user-images.githubusercontent.com/47206816/82469187-47798500-9af6-11ea-9b9b-2a344dbdd998.png)
n = n1? M, n1ij∼ N(0,1),   The meaning of each parameter

**Comment by zsyOAOA** [comment]
For any source clean image I \in R^{h \times w}, we generate M, n^1 \in R^{h \times w}, respectively, then the noisy image is obtained by I + n^1 \odot M.

**Comment by CLJcode** [comment]
I don't kown what kind of  operation  'odot'  is . In your code, I only see the 'I+M'. What does the mean ing of n1? gusssion? thank you.

**Comment by zsyOAOA** [comment]
odot means pixel-wise multiplication. Please check the code ./datasets/DenoisingDatasets.py line 106.
