### ISSUE TITLE
Can’t find the supplementary material in the paper

### ISSUE THREAD

**Issue by wsin184** [zsyOAOA/VDNet#5]
Hi Author.
I can't find the supplementary material in the paper.Could you please give me the supplementary material?

**Comment by zsyOAOA** [comment]
@wsin184 I had uploaded the supplementary material, please have a check. Thanks!
https://github.com/zsyOAOA/VDNet/blob/master/supplementary_nips.pdf

**Comment by wsin184** [comment]
谢谢你！
