### ISSUE TITLE
Is using SIDD to train should be train_benchmark.py instead of train_simulation.py?

### ISSUE THREAD

**Issue by jiaoxijie** [zsyOAOA/VDNet#7]
In your readme, you write for SIDD_Medium dataset, the training code should be ：
python train_simulation.py --SIDD_dir sidd_data_path --eps2 1e-6

I read your code. I think it should be python train_benchmark.py --SIDD_dir sidd_data_path --eps2 1e-6

**Comment by zsyOAOA** [comment]
Yes, you're right. It's my mistake. I had corrected it.
